import React, { useState } from 'react';
import DashboardLayout from '../DashboardLayout';
import apiService from '../api/client';
import { useToast } from '../context/NotificationContext';

function SectionEditor({ section, index, onChange, onRemove }) {
  return (
    <div className="border rounded p-3 mb-3 bg-white dark:bg-slate-800">
      <div className="flex items-center justify-between mb-2">
        <input
          className="w-3/4 p-2 border rounded"
          placeholder={`Section ${index + 1} title`}
          value={section.title}
          onChange={(e) => onChange(index, { ...section, title: e.target.value })}
        />
        <button
          className="ml-2 px-3 py-1 bg-red-600 text-white rounded"
          onClick={() => onRemove(index)}
        >
          Remove
        </button>
      </div>
      <textarea
        rows={4}
        className="w-full p-2 border rounded"
        placeholder="Section body / notes"
        value={section.body}
        onChange={(e) => onChange(index, { ...section, body: e.target.value })}
      />
    </div>
  );
}

export default function ReportBuilder() {
  const [title, setTitle] = useState('Analytics Report');
  const [subtitle, setSubtitle] = useState('Generated by the platform');
  const [sections, setSections] = useState([
    { title: 'Executive Summary', body: '' },
    { title: 'Key Metrics', body: '' },
  ]);
  const [format, setFormat] = useState('pdf');
  const [loading, setLoading] = useState(false);
  const { success, error } = useToast();

  const addSection = () => setSections((s) => [...s, { title: '', body: '' }]);

  const updateSection = (idx, updated) =>
    setSections((s) => s.map((sec, i) => (i === idx ? updated : sec)));

  const removeSection = (idx) => setSections((s) => s.filter((_, i) => i !== idx));

  const onGenerate = async () => {
    try {
      setLoading(true);
      const payload = { title, subtitle, sections };
      const res = await apiService.generateStructuredReport(payload, format);
      // res is a Blob because we requested responseType blob
      const blob = new Blob([res], { type: format === 'pptx' ? 'application/vnd.openxmlformats-officedocument.presentationml.presentation' : 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = format === 'pptx' ? 'analytics_report.pptx' : 'analytics_report.pdf';
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
      success('Report generated and download started');
    } catch (err) {
      console.error(err);
      error('Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="p-6">
        <h1 className="text-2xl font-semibold mb-4">Report Builder</h1>

        <div className="mb-4">
          <label className="block mb-1 font-medium">Title</label>
          <input value={title} onChange={(e) => setTitle(e.target.value)} className="w-full p-2 border rounded" />
        </div>

        <div className="mb-4">
          <label className="block mb-1 font-medium">Subtitle</label>
          <input value={subtitle} onChange={(e) => setSubtitle(e.target.value)} className="w-full p-2 border rounded" />
        </div>

        <div className="mb-4">
          <label className="block mb-2 font-medium">Sections</label>
          {sections.map((section, idx) => (
            <SectionEditor key={idx} section={section} index={idx} onChange={updateSection} onRemove={removeSection} />
          ))}
          <button onClick={addSection} className="px-3 py-2 bg-blue-600 text-white rounded">Add Section</button>
        </div>

        <div className="mb-6">
          <label className="block mb-1 font-medium">Output Format</label>
          <select value={format} onChange={(e) => setFormat(e.target.value)} className="p-2 border rounded">
            <option value="pdf">PDF</option>
            <option value="pptx">PowerPoint (PPTX)</option>
          </select>
        </div>

        <div>
          <button onClick={onGenerate} disabled={loading} className="px-4 py-2 bg-green-600 text-white rounded">
            {loading ? 'Generating…' : 'Generate Report'}
          </button>
        </div>
      </div>
    </DashboardLayout>
  );
}
