import React, { useState } from 'react';
import DashboardLayout from '../DashboardLayout';
import apiService from '../api/client';
import { useToast } from '../context/NotificationContext';

function SectionEditor({ section, index, onChange, onRemove }) {
  return (
    <div className="border rounded p-3 mb-3 bg-white dark:bg-slate-800">
      <div className="flex items-center justify-between mb-2">
        <input
          className="w-3/4 p-2 border rounded"
          placeholder={`Section ${index + 1} title`}
          value={section.title}
          onChange={(e) => onChange(index, { ...section, title: e.target.value })}
        />
        <button
          className="ml-2 px-3 py-1 bg-red-600 text-white rounded"
          onClick={() => onRemove(index)}
        >
          Remove
        </button>
      </div>
      <textarea
        rows={4}
        className="w-full p-2 border rounded"
        placeholder="Section body / notes"
        value={section.body}
        onChange={(e) => onChange(index, { ...section, body: e.target.value })}
      />
    </div>
  );
}

export default function ReportBuilder() {
  const [title, setTitle] = useState('Analytics Report');
  const [subtitle, setSubtitle] = useState('Generated by the platform');
  const [sections, setSections] = useState([
    { title: 'Executive Summary', body: '' },
    { title: 'Key Metrics', body: '' },
  ]);
  const [format, setFormat] = useState('pdf');
  const [loading, setLoading] = useState(false);
  const { success, error } = useToast();

  const addSection = () => setSections((s) => [...s, { title: '', body: '' }]);

  const updateSection = (idx, updated) =>
    setSections((s) => s.map((sec, i) => (i === idx ? updated : sec)));

  const removeSection = (idx) => setSections((s) => s.filter((_, i) => i !== idx));

  const onGenerate = async () => {
    try {
      setLoading(true);
      // Ensure sections include any captured images
      const payload = { title, subtitle, sections };
      const res = await apiService.generateStructuredReport(payload, format);
      // res is a Blob because we requested responseType blob
      const blob = new Blob([res], { type: format === 'pptx' ? 'application/vnd.openxmlformats-officedocument.presentationml.presentation' : 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = format === 'pptx' ? 'analytics_report.pptx' : 'analytics_report.pdf';
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
      success('Report generated and download started');
    } catch (err) {
      console.error(err);
      error('Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  // Scan DOM for canvas elements to allow attaching chart images
  const [availableCanvases, setAvailableCanvases] = React.useState([]);
  const [dragSrcIndex, setDragSrcIndex] = React.useState(null);

  // Simple templates
  const templates = [
    {
      id: 'exec_summary',
      name: 'Executive Summary Template',
      sections: [
        { title: 'Executive Summary', body: '' },
        { title: 'Key Findings', body: '' },
        { title: 'Recommendations', body: '' },
      ],
    },
    {
      id: 'full_report',
      name: 'Full Analytics Report',
      sections: [
        { title: 'Executive Summary', body: '' },
        { title: 'Data Overview', body: '' },
        { title: 'Metrics & Trends', body: '' },
        { title: 'Anomalies', body: '' },
        { title: 'Appendix', body: '' },
      ],
    },
  ];

  const applyTemplate = (tid) => {
    const t = templates.find((x) => x.id === tid);
    if (t) setSections(t.sections.map((s) => ({ ...s })));
  };

  const scanCanvases = () => {
    try {
      const canvases = Array.from(document.querySelectorAll('canvas'));
      const list = canvases.map((c, i) => ({
        id: c.id || `canvas-${i}`,
        el: c,
        label: c.getAttribute('data-chart-name') || c.id || `Chart ${i + 1}`,
      }));
      setAvailableCanvases(list);
    } catch (err) {
      console.warn('canvas scan failed', err);
      setAvailableCanvases([]);
    }
  };

  React.useEffect(() => {
    // initial scan
    scanCanvases();
    // also listen for DOM changes (simple interval refresh)
    const t = setInterval(scanCanvases, 3000);
    return () => clearInterval(t);
  }, []);

  const attachCanvasToSection = (sectionIndex, canvasEntry) => {
    try {
      const canvas = canvasEntry.el;
      const dataUrl = canvas.toDataURL('image/png');
      updateSection(sectionIndex, { ...sections[sectionIndex], image: dataUrl });
      success(`Attached ${canvasEntry.label} to section ${sectionIndex + 1}`);
    } catch (err) {
      console.error('attach failed', err);
      error('Failed to attach chart image');
    }
  };

  return (
    <DashboardLayout>
      <div className="p-6">
        <h1 className="text-2xl font-semibold mb-4">Report Builder</h1>

        <div className="mb-4">
          <label className="block mb-1 font-medium">Title</label>
          <input value={title} onChange={(e) => setTitle(e.target.value)} className="w-full p-2 border rounded" />
        </div>

        <div className="mb-4">
          <label className="block mb-1 font-medium">Subtitle</label>
          <input value={subtitle} onChange={(e) => setSubtitle(e.target.value)} className="w-full p-2 border rounded" />
        </div>

        <div className="mb-4">
          <label className="block mb-2 font-medium">Sections</label>
          {sections.map((section, idx) => (
            <div key={idx}
              draggable
              onDragStart={(e) => { setDragSrcIndex(idx); e.dataTransfer.setData('text/plain', String(idx)); }}
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => {
                e.preventDefault();
                const src = Number(e.dataTransfer.getData('text/plain'));
                const dst = idx;
                if (!Number.isNaN(src) && src !== dst) {
                  const copy = [...sections];
                  const [moved] = copy.splice(src, 1);
                  copy.splice(dst, 0, moved);
                  setSections(copy);
                }
                setDragSrcIndex(null);
              }}
            >
              <SectionEditor section={section} index={idx} onChange={updateSection} onRemove={removeSection} />

              <div className="flex items-center gap-2 mb-4">
                <select
                  className="p-2 border rounded"
                  onChange={(e) => {
                    const sel = availableCanvases.find((c) => c.id === e.target.value);
                    if (sel) attachCanvasToSection(idx, sel);
                  }}
                  defaultValue=""
                >
                  <option value="">Attach a chart (canvas)...</option>
                  {availableCanvases.map((c) => (
                    <option key={c.id} value={c.id}>{c.label}</option>
                  ))}
                </select>

                {section.image && (
                  <div className="flex items-center gap-2">
                    <img alt={`preview-${idx}`} src={section.image} className="w-28 h-20 object-contain border" />
                    <button onClick={() => updateSection(idx, { ...section, image: undefined })} className="px-2 py-1 bg-red-600 text-white rounded">Remove Image</button>
                  </div>
                )}
              </div>
            </div>
          ))}
          <button onClick={addSection} className="px-3 py-2 bg-blue-600 text-white rounded">Add Section</button>
        </div>

        <div className="mb-6">
          <label className="block mb-1 font-medium">Output Format</label>
          <select value={format} onChange={(e) => setFormat(e.target.value)} className="p-2 border rounded">
            <option value="pdf">PDF</option>
            <option value="pptx">PowerPoint (PPTX)</option>
          </select>
        </div>

        <div>
          <div className="flex items-center gap-3">
            <button onClick={onGenerate} disabled={loading} className="px-4 py-2 bg-green-600 text-white rounded">
              {loading ? 'Generating…' : 'Generate Report'}
            </button>
            <div className="ml-4">
              <label className="block text-sm mb-1">Templates</label>
              <select onChange={(e) => applyTemplate(e.target.value)} className="p-2 border rounded">
                <option value="">Apply template...</option>
                {templates.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}
              </select>
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
